name: Terraform Destroy Pipeline

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    env:
      AWS_BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}
      AWS_BUCKET_KEY_NAME: ${{ vars.AWS_BUCKET_KEY_NAME }}
      AWS_DYNAMODB_TABLE: ${{ vars.AWS_DYNAMODB_TABLE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      WORKING_DIRECTORY: ./terraform

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.AWS_BUCKET_NAME }}" \
            -backend-config="key=${{ env.AWS_BUCKET_KEY_NAME }}" \
            -backend-config="region=eu-central-1" \
            -backend-config="dynamodb_table=${{ env.AWS_DYNAMODB_TABLE }}"
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Destroy
        run: terraform destroy -var-file="env-${{ vars.ENVIRONMENT_NAME }}.tfvars" -auto-approve
        working-directory: ${{ env.WORKING_DIRECTORY }}
