name: Terraform Plan Pipeline

on:
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    env:
      AWS_BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}
      AWS_BUCKET_KEY_NAME: ${{ vars.AWS_BUCKET_KEY_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      WORKING_DIRECTORY: ./terraform

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.AWS_BUCKET_NAME }}" \
            -backend-config="key=${{ env.AWS_BUCKET_KEY_NAME }}" \
            -backend-config="region=eu-central-1"
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.WORKING_DIRECTORY }}
